# Generated by Django 4.2.1 on 2023-05-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
    ]
