# Generated by Django 4.2.1 on 2023-05-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20230516_0442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='spam',
        ),
    ]
