# Generated by Django 4.2.1 on 2023-05-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_remove_email_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
