# Generated by Django 4.2.1 on 2023-05-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_remove_email_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
